# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'KMMTApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for nibras_iOSApp
	pod 'SkyFloatingLabelTextField', '~> 3.0'

  
  target 'KMMTAppTests' do
    inherit! :search_paths
    # Pods for testing

  end

  target 'KMMTAppUITests' do
    # Pods for testing

  end

end
